name: 🚀 Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия релиза (например: v1.0.2)'
        required: true
        default: 'v1.0.0'
        type: string
      prerelease:
        description: 'Отметить как pre-release (тестовая версия)'
        required: false
        default: false
        type: boolean
      draft:
        description: 'Создать как черновик'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔧 Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: 📦 Install dependencies
      run: go mod tidy

    - name: 🔨 Build for multiple platforms
      run: |
        # Создаем директорию для билдов
        mkdir -p dist
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/batmon-linux-amd64
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/batmon-linux-arm64
        
        # macOS AMD64 (Intel)
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/batmon-darwin-amd64
        
        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/batmon-darwin-arm64
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/batmon-windows-amd64.exe
        
        # Windows ARM64
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o dist/batmon-windows-arm64.exe

    - name: 📦 Create archives
      run: |
        cd dist
        
        # Создаем tar.gz для Unix-подобных систем
        tar -czf batmon-linux-amd64.tar.gz batmon-linux-amd64
        tar -czf batmon-linux-arm64.tar.gz batmon-linux-arm64
        tar -czf batmon-darwin-amd64.tar.gz batmon-darwin-amd64
        tar -czf batmon-darwin-arm64.tar.gz batmon-darwin-arm64
        
        # Создаем zip для Windows
        zip batmon-windows-amd64.zip batmon-windows-amd64.exe
        zip batmon-windows-arm64.zip batmon-windows-arm64.exe
        
        # Создаем checksums
        sha256sum *.tar.gz *.zip > checksums.txt

    - name: 📊 Get version info
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "is_manual=true" >> $GITHUB_OUTPUT
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "is_manual=false" >> $GITHUB_OUTPUT
        else
          echo "ERROR: Workflow triggered unexpectedly" >&2
          exit 1
        fi

    - name: 🏷️ Create tag for manual release
      if: steps.version.outputs.is_manual == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        git push origin ${{ steps.version.outputs.version }}

    - name: 🚀 Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt
        draft: ${{ github.event.inputs.draft == 'true' }}
        prerelease: ${{ github.event.inputs.prerelease == 'true' }}
        body: |
          ## 🔋 BatMon ${{ steps.version.outputs.version }}
          
          Интеллектуальный мониторинг батареи MacBook с детальной аналитикой.
          
          ### 📥 Быстрая установка
          
          **Для пользователей Go:**
          ```bash
          go install github.com/region23/batmon@${{ steps.version.outputs.version }}
          ```
          
          **Для остальных - скачайте готовый бинарник:**
          
          #### 🍎 macOS
          - **Apple Silicon (M1/M2/M3)**: `batmon-darwin-arm64.tar.gz`
          - **Intel**: `batmon-darwin-amd64.tar.gz`
          
          #### 🐧 Linux
          - **AMD64/x86_64**: `batmon-linux-amd64.tar.gz`
          - **ARM64**: `batmon-linux-arm64.tar.gz`
          
          #### 🪟 Windows
          - **AMD64/x86_64**: `batmon-windows-amd64.zip`
          - **ARM64**: `batmon-windows-arm64.zip`
          
          ### 🚀 Как использовать
          
          1. Скачайте архив для вашей платформы
          2. Распакуйте: `tar -xzf batmon-*.tar.gz` или разархивируйте zip
          3. Запустите: `./batmon` (или `batmon.exe` на Windows)
          4. Выберите "Полный анализ батареи (100% → 0%)" для основного сценария
          
          ### ✨ Основные возможности
          - 🔋 Полный анализ батареи от 100% до 0%
          - 📊 Интерактивные графики и детальная статистика
          - 📄 Экспорт отчетов в HTML/Markdown
          - 🌡️ Мониторинг температуры батареи
          - 💡 Персонализированные рекомендации по замене
          - 🎯 Кроссплатформенность (macOS, Linux, Windows)
          
          ### 🛡️ Безопасность
          - ✅ Проверьте контрольные суммы: `sha256sum -c checksums.txt`
          - ✅ Код полностью открытый на [GitHub](https://github.com/region23/batmon)
          
          ### 📊 Совместимость
          - ✅ **macOS**: 12.0+ (Monterey и новее)
          - ✅ **Linux**: Любой дистрибутив с systemd (Ubuntu, CentOS, etc)
          - ✅ **Windows**: 10+ (экспериментально)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 📤 Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: batmon-${{ steps.version.outputs.version }}
        path: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt
        retention-days: 30