name: 🚀 Build and Release macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия релиза (например: v1.0.2)'
        required: true
        default: 'v1.0.0'
        type: string
      prerelease:
        description: 'Отметить как pre-release (тестовая версия)'
        required: false
        default: false
        type: boolean
      draft:
        description: 'Создать как черновик'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  actions: read
  security-events: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔧 Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: 📦 Install dependencies
      run: go mod tidy

    - name: 🏗️ Install appify
      run: go install github.com/machinebox/appify@latest

    - name: 🔨 Build for Apple Silicon (arm64)
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o batmon-arm64

    - name: 🔨 Build for Intel (amd64)  
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o batmon-amd64

    - name: 🔗 Create universal binary
      run: |
        lipo -create -output batmon-universal batmon-arm64 batmon-amd64
        chmod +x batmon-universal

    - name: 📱 Create macOS App Bundle
      run: |
        appify -name "BatMon" -icon "./logo.png" -id "com.batmon.app" -version "1.0" ./batmon-universal

    - name: 📦 Package App for Distribution
      run: |
        # Create a clean directory for distribution
        mkdir -p dist
        mv BatMon.app dist/
        cd dist
        zip -r BatMon.zip BatMon.app
        # Create checksum
        shasum -a 256 BatMon.zip > BatMon.zip.sha256

    - name: 📊 Get version info
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
          echo "is_manual=true" >> $GITHUB_OUTPUT
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
          echo "is_manual=false" >> $GITHUB_OUTPUT
        else
          echo "version=dev-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo "is_tag=false" >> $GITHUB_OUTPUT
          echo "is_manual=false" >> $GITHUB_OUTPUT
        fi

    - name: 🏷️ Create tag for manual release
      if: steps.version.outputs.is_manual == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        git push origin ${{ steps.version.outputs.version }}

    - name: 🚀 Create Release (for tags only)
      if: steps.version.outputs.is_tag == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: |
          dist/BatMon.zip
          dist/BatMon.zip.sha256
        draft: ${{ github.event.inputs.draft == 'true' }}
        prerelease: ${{ github.event.inputs.prerelease == 'true' }}
        body: |
          ## 🔋 BatMon ${{ steps.version.outputs.version }}
          
          ### 📥 Установка для обычных пользователей
          
          1. **Скачайте**: `BatMon.zip` из списка файлов ниже
          2. **Распакуйте**: Двойной клик по скачанному zip-файлу  
          3. **Запустите**: Двойной клик по `BatMon.app`
          4. **Готово!** Программа откроется с приветственным экраном
          
          ### ✨ Что нового
          - Полный анализ батареи MacBook (100% → 0%)
          - Предотвращение засыпания во время тестирования  
          - Быстрая диагностика состояния батареи
          - Детальные отчеты с рекомендациями по замене
          - Интерактивный интерфейс с цветными индикаторами
          
          ### 🛡️ Безопасность
          - Файл подписан контрольной суммой SHA256
          - Проверить: `shasum -a 256 BatMon.zip` (должно совпасть с .sha256 файлом)
          
          ### 💻 Совместимость
          - ✅ MacBook с Apple Silicon (M1, M2, M3)
          - ✅ MacBook с Intel процессорами
          - ✅ macOS 12.0+ (Monterey и новее)
          
          ### 🆘 Поддержка
          Если macOS показывает предупреждение о безопасности:
          1. Откройте **Системные настройки** → **Конфиденциальность и безопасность**
          2. Найдите сообщение о BatMon и нажмите **Все равно открыть**
          3. Или запустите в Терминале: `xattr -d com.apple.quarantine /path/to/BatMon.app`
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 📤 Upload Artifact (for all builds)
      uses: actions/upload-artifact@v4
      with:
        name: BatMon-${{ steps.version.outputs.version }}
        path: |
          dist/BatMon.zip
          dist/BatMon.zip.sha256
        retention-days: 30